### ISSUE TITLE
Before the HOL document

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Azure-security-and-management#8]
Task 3 # 4 (line 151) image is not showing

**Comment by jtuliani** [comment]
Addressed in june-2018-update branch

**Comment by DawnmarieDesJardins** [comment]
Reopening issue.  I'm still seeing:
X The pin icon is called out on the LabVM blade.
No image showing

**Comment by DawnmarieDesJardins** [comment]
All good – that’s why we QC.  Four eyes are better than two! 😊
Dawnmarie
